#pragma once

#define DIODE_DIRECTION COL2ROW

#define EE_HANDS
#define SPLIT_USB_DETECT

#define MATRIX_ROW_PINS \
    { GP11, GP12, GP13, GP10 }

#define MATRIX_COL_PINS \
    { GP22, GP21, GP20, GP19, GP18, GP17 }

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

#define SERIAL_USART_TX_PIN GP1
#define SERIAL_USART_RX_PIN GP0
#define SERIAL_USART_FULL_DUPLEX

#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP8
#define I2C1_SCL_PIN GP9

#define IGNORE_MOD_TAP_INTERRUPT

#ifdef POINTING_DEVICE_ENABLE
    #define ANALOG_JOYSTICK_X_AXIS_PIN  B4
    #define ANALOG_JOYSTICK_Y_AXIS_PIN  B5
    #define ANALOG_JOYSTICK_CLICK_PIN  E6
#endif

#ifdef WPM_ENABLE
    #define SPLIT_WPM_ENABLE
#endif

#ifdef AUDIO_ENABLE
    #define AUDIO_PIN B5
    #define AUDIO_CLICKY
#endif
