#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

#define POINTING_DEVICE_DEBUG

#define ANALOG_JOYSTICK_X_AXIS_PIN GP26
#define ANALOG_JOYSTICK_Y_AXIS_PIN GP28
// #define ANALOG_JOYSTICK_CLICK_PIN GP26

// The divisor used to slow down movement. (lower makes it faster)
#define ANALOG_JOYSTICK_SPEED_REGULATOR 5
#define POINTING_DEVICE_ROTATION_180

// #define IGNORE_MOD_TAP_INTERRUPT

//#define RGB_DI_PIN GP23
#define WS2812_DI_PIN GP23
#define RGBLIGHT_LED_COUNT 1

#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_TWINKLE

#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RGB_TEST
